apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb-container
  template:
    metadata:
      labels:
        app: mongodb-container
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
  
