apiVersion: batch/v1
kind: Job
metadata:
  name: python-app-job
spec:
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: saosj/cda:v4
          env:
          - name: HOST_BD
            value: "mongodb-container"
          - name: HOST_BD_PORT
            value: "27017"
      restartPolicy: Never
  backoffLimit: 0
