apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http         # nombre descriptivo del puerto
      port: 9200
      targetPort: 9200
    - name: transport    # otro nombre descriptivo
      port: 9300
      targetPort: 9300
